version: 1.0.{build}
image:
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015
- Ubuntu1804
    
environment:
  matrix:
  - arch_compiler: i386_msvc
  - arch_compiler: x64_msvc
  - arch_compiler: i386_gcc
  - arch_compiler: x64_gcc
 # - arch_compiler: i386_mingw
 # - arch_compiler: x64_mingw


matrix:
  exclude:
    - image: Ubuntu1804
      arch_compiler: i386_msvc

    - image: Ubuntu1804
      arch_compiler: x64_msvc

    - image: Visual Studio 2019
      arch_compiler: i386_gcc

    - image: Visual Studio 2019
      arch_compiler: x64_gcc

    - image: Visual Studio 2017
      arch_compiler: i386_gcc

    - image: Visual Studio 2017
      arch_compiler: x64_gcc

    - image: Visual Studio 2015
      arch_compiler: i386_gcc

    - image: Visual Studio 2015
      arch_compiler: x64_gcc

    - image: Visual Studio 2015
      arch_compiler: i386_mingw

    - image: Visual Studio 2015
      arch_compiler: x64_mingw

    - image: Visual Studio 2017
      arch_compiler: i386_mingw

    - image: Visual Studio 2017
      arch_compiler: x64_mingw
      
    - image: Visual Studio 2019
      arch_compiler: i386_mingw

    - image: Visual Studio 2019
      arch_compiler: x64_mingw

    - image: Ubuntu1804
      arch_compiler: i386_mingw

    - image: Ubuntu1804
      arch_compiler: x64_mingw
      
init:
    - ps:  $env:buildType = "-DCMAKE_BUILD_TYPE=Release" 
    - ps:  $env:installDir = "-DCMAKE_INSTALL_PREFIX=./install"
    - ps:  $env:ssblDir = "-DSSBL_INSTALL_DIR=./ssbl/build/install"
    - ps: >-
        switch($env:arch_compiler) {
            i386_msvc
            {
                Set-Variable -Name "archVS2019" -Value "Win32"
                Set-Variable -Name "gen2015" -Value "Visual Studio 14 2015"
                Set-Variable -Name "gen2017" -Value "Visual Studio 15 2017"
            }
            x64_msvc
            {
                Set-Variable -Name "archVS2019" -Value "x64"
                Set-Variable -Name "archGCC" -Value "Win64"
                Set-Variable -Name "gen2015" -Value "Visual Studio 14 2015 Win64"
                Set-Variable -Name "gen2017" -Value "Visual Studio 15 2017 Win64"
            }
            i386_gcc
            {
                $env:additionalCMakeFlags = "-DSSBL_32BIT=1"
            }
            i386_mingw
            {
                $env:additionalCMakeFlags = "-DSSBL_32BIT=1"
            }
            deafult
            {
            
            }
        }
    - ps: >-
        switch($env:APPVEYOR_BUILD_WORKER_IMAGE) {
            "Visual Studio 2019"
            {
                if ($env:arch_compiler -like '*msvc*') 
                { 
                    $env:generator = "Visual Studio 16 2019"
                    $env:genarch = "-A""$archVS2019"""
                } 
                else 
                { 
                    $env:generator = "Eclipse CDT4 - MinGW Makefiles"
                }
            }
            "Visual Studio 2017"
            {
                if ($env:arch_compiler -like '*msvc*') 
                { 
                    $env:generator ="$gen2017"
                }
                else
                { 
                    $env:generator = "Eclipse CDT4 - MinGW Makefiles"
                }
            }
            "Visual Studio 2015"
            {
                if ($env:arch_compiler -like '*msvc*') 
                { 
                    $env:generator ="$gen2015"
                }
                else 
                { 
                    $env:generator = "Eclipse CDT4 - MinGW Makefiles"
                }
            }
            "Ubuntu1804"
            {
                if ($env:arch_compiler -like '*gcc*') 
                { 
                    $env:generator ="Eclipse CDT4 - Unix Makefiles"
                }
                else 
                { 
                    $env:generator = "Eclipse CDT4 - MinGW Makefiles"
                }
            }
        }


install:
install:
    - sh: sudo apt-get update
    - sh: sudo apt-get --assume-yes install  gcc-multilib g++-multilib
    
before_build:
    - ps: git clone -q https://github.com/SickScan/sick_scan_base.git ssbl
    - ps: cd ssbl
    - ps: mkdir build
    - ps: cd build
    - ps: cmake  -G"$env:generator" $env:genarch $env:additionalCMakeFlags $env:buildType $env:installDir --no-warn-unused-cli ..
    - ps: cmake --build . --target install --config Release
    - ps: cd ../..
    - ps: cmake  -G"$env:generator" $env:genarch $env:additionalCMakeFlags $env:ssblDir -Bbuild .
    
build_script:
- ps: cmake --build build --config Release